name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This is the job for merge requests
  install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: echo I am installing stuff with npm install... 

  unit-tests:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Unit Tests
        run: |
          echo I am running npm run test,
          echo wow, everything is passing so far.
  
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    environment: 
      name: main
    steps:
      - name: Deploy artifacts
        run: echo I am deploying the artifacts!
